RAY_CONFIG:
  # autoscaling
  NUM_CPUS: 0.8
  NUM_GPUS: 0.2
  MAX_CONCURRENT_QUERIES: 5
  NUM_REQUESTS_PER_REPLICA: 1
  MIN_REPLICAS: 1
  INIT_REPLICAS: 1
  MAX_REPLICAS: 200

  # scale 
  OMP_NUM_THREADS: 1 

  # batch infer
  MAX_BATCH_SIZE: 5
  BATCH_TIMEOUT: 0.1